---
title: "Influenza A H7N9 in China, 2013"
format: dashboard
theme: lux
author: "By: Ester Nepolo"
---

```{r}
# Load packages 
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, outbreaks, bslib, bsicons, shiny, 
               rgeoboundaries, plotly, htmltools, reactable, sparkline)

# view data
 # head(outbreaks::fluH7N9_china_2013)
```
```{r}
# Calculate key matrix

# Total cases
province_summary <- fluH7N9_china_2013 %>% 
  group_by(province) %>% 
  summarise(total_cases = n()) 

total_cases <- nrow(fluH7N9_china_2013)


# Total deaths

total_deaths <- fluH7N9_china_2013 %>% 
  filter(outcome == "Death") %>% 
  nrow()


# Total hospitalisation

total_hosp <- fluH7N9_china_2013 %>% 
  filter(!is.na(date_of_hospitalisation)) %>% 
           nrow()

```


```{r}

### MAP OF CASES PER PROVINCE
province_summary <- fluH7N9_china_2013 %>% 
  group_by(province) %>% 
  summarise(total_cases = n()) 

china_map <- rgeoboundaries::gb_adm1("china")

# Check the keys to see if join will be successful
# setdiff(province_summary$province, china_map$shapeName)
# setdiff(china_map$shapeName, province_summary$province)
# Some work to be done to harmonize these

china_map <- china_map %>%
  # Remove the strings Province, Municipality and Autonomous Region 
  # to allow matching
  mutate(province = str_trim(
    str_remove(shapeName, "Province|Municipality|Autonomous Region")
  ))

# Check if join will work fine
# setdiff(province_summary$province, china_map$province)

# Fix Guangdong, which based on a quick Google is actually Guangzhou
china_map <- china_map %>% 
  mutate(province = if_else(province == "Guangzhou", "Guangdong", province)) 
  
# Check again
# setdiff(province_summary$province, china_map$province)

# Now join
china_map_joined <- 
  left_join(china_map, province_summary, by = "province") %>% 
  # Create tooltip label 
  mutate(tooltip_label = paste0(province, ": ", total_cases))

china_map_plot <- ggplot(china_map_joined) +
  geom_sf(aes(fill = total_cases, text = tooltip_label)) + 
  theme_void() +
  labs(fill = "Number of Cases") + 
  theme(legend.position = "none")

china_map_plot_ggplotly <- 
  ggplotly(china_map_plot, tooltip = "text")
```

```{r}
# china_map_plot_ggplotly
```

```{r}

# Plot Number of Cases per Province

province_summary <- fluH7N9_china_2013 %>% 
  group_by(province) %>% 
  summarise(total_cases = n())  %>% 
  arrange(desc(total_cases)) %>% 
 mutate(tooltip_label = paste(province, 
                               total_cases, 
                               sep = ": ")) 

  province_plot <- ggplot(province_summary, 
                          aes(x = total_cases,
                              y = reorder(province, total_cases),
                              fill = total_cases,
                              text = tooltip_label)) + 
  geom_col(fill = "steelblue") + 
  labs( x = "Number of Cases", y = NULL) + 
  theme_minimal()

province_plot_ggplotly <- 
  ggplotly(province_plot, tooltip = "text")

# province_plot_ggplotly


```



# HOME 

## Row 1 {height="25%"}

```{r}
value_box(
  title = "Total cases",
  value = total_cases,
  showcase = bsicons::bs_icon("virus"),
  theme = value_box_theme(bg = "#518fd6")
)
```

```{r}
value_box(
  title = "Total Hospitalisations",
  value = total_hosp,
  showcase = bsicons::bs_icon("hospital"),
  theme = value_box_theme(bg = "#214773")
)
```

```{r}
value_box(
  title = "Total deaths",
  value = total_deaths,
  showcase = bsicons::bs_icon("file-medical"),
  theme = value_box_theme(bg = "#3f71ab")
)
```

## Row 2 {height="75%"}

### {width="30%"}

```{r title = "Number of Cases by Province"}

province_plot_ggplotly

```


### {width="70%"}

```{r title = "Map of Provinces by Number of Cases" }
china_map_plot_ggplotly
```


# DOWNLOAD DATA


```{r}
library(htmltools)

htmltools::browsable(
  tagList(
    reactable(fluH7N9_china_2013, 
              elementId = "china-table", 
              searchable = T, 
              filterable = T), 
    
tags$button("Download as CSV", 
            onclick = "Reactable.downloadDataCSV('china-table')")
  )
)
```

